#include "driver/i2c_master.h"
#include "freertos/FreeRTOS.h"
#include "s31fl3741a.h"
#include "station_map.h"



//Red Line
station_t ALEWIFE_SOUTH     = {CS28_SW1, 2};
station_t ALEWIFE_NORTH     = {CS30_SW1, 2};
station_t ALEWIFE_TO_DAVIS  = {CS18_SW1, 2};
station_t DAVIS_TO_ALEFWIFE = {CS17_SW1, 2};
station_t DAVIS_SOUTH       = {CS22_SW2, 2};
station_t DAVIS_NORTH       = {CS23_SW2, 2};
station_t DAVIS_TO_PORTER   = {CS25_SW2, 2};
station_t PORTER_TO_DAVIS   = {CS24_SW2, 2};
station_t PORTER_SOUTH      = {CS16_SW6, 1};
station_t PORTER_NORTH      = {CS29_SW6, 1};
station_t PORTER_TO_HARVARD = {CS29_SW5, 1};
station_t HARVARD_TO_PORTER = {CS18_SW3, 2};
station_t HARVARD_SOUTH = {CS15_SW3, 2};
station_t HARVARD_NORTH = {CS17_SW3, 2};
station_t HARVARD_TO_CENTRAL = {CS16_SW3, 2};
station_t CENTRAL_TO_HARVARD = {CS13_SW4, 2};
station_t CENTRAL_SOUTH = {CS15_SW4, 2};
station_t CENTRAL_NORTH = {CS14_SW4, 2};
station_t CENTRAL_TO_KENDALL = {CS13_SW5, 2};
station_t KENDALL_TO_CENTRAL = {CS14_SW5, 2};
station_t KENDALL_SOUTH = {CS16_SW5, 2};
station_t KENDALL_NORTH = {CS15_SW5, 2};
station_t KENDALL_TO_CHARLES = {CS24_SW6, 2};
station_t CHARLES_TO_KENDALL = {CS25_SW6, 2};
station_t CHARLES_SOUTH = {CS22_SW6, 2};
station_t CHARLES_NORTH = {CS23_SW6, 2};
station_t CHARLES_TO_PARKRED = {CS35_SW9, 2};
station_t PARKRED_TO_CHARLES = {CS33_SW9, 2};
station_t PARKRED_SOUTH = {CS39_SW9, 2};
station_t PARKRED_NORTH = {CS37_SW9, 2};
station_t PARKRED_TO_DOWNTOWNRED = {CS32_SW9, 2};
station_t DOWNTOWNRED_TO_PARKRED = {CS28_SW9, 2};
station_t DOWNTOWNRED_SOUTH = {CS34_SW9, 2};
station_t DOWNTOWNRED_NORTH = {CS18_SW9, 2};
station_t DOWNTOWNRED_TO_SOUTH = {CS17_SW9, 2};
station_t SOUTH_TO_DOWNTOWNRED = {CS30_SW9, 2};
station_t SOUTH_SOUTH = {CS14_SW7, 2};
station_t SOUTH_NORTH = {CS4_SW7, 2};
station_t SOUTH_TO_BROADWAY_1 = {CS10_SW7, 2};
station_t BROADWAY_TO_SOUTH_1 = {CS34_SW7, 2};
station_t SOUTH_TO_BROADWAY_2 = {CS38_SW7, 2};
station_t BROADWAY_TO_SOUTH_2 = {CS39_SW7, 2};
station_t BROADWAY_SOUTH = {CS32_SW7, 2};
station_t BROADWAY_NORTH = {CS5_SW7, 2};
station_t BROADWAY_TO_ANDREW = {CS4_SW3, 1};
station_t ANDREW_TO_BROADWAY = {CS3_SW4, 1};
station_t ANDREW_SOUTH = {CS6_SW4, 1};
station_t ANDREW_NORTH = {CS15_SW4, 1};
station_t ANDREW_TO_JFK = {CS33_SW4, 1};
station_t JFK_TO_ANDREW = {CS29_SW4, 1};
station_t JFK_SOUTH = {CS7_SW4, 1};
station_t JFK_NORTH = {CS31_SW4, 1};
station_t JFK_TO_SAVIN = {CS36_SW5, 2};
station_t SAVIN_TO_JFK = {CS35_SW5, 2};
station_t SAVIN_SOUTH = {CS34_SW5, 2};
station_t SAVIN_NORTH = {CS33_SW5, 2};
station_t SAVIN_TO_FIELDS = {CS38_SW4, 2};
station_t FIELDS_TO_SAVIN = {CS33_SW4, 2};
station_t FIELDS_SOUTH = {CS32_SW4, 2};
station_t FIELDS_NORTH = {CS34_SW4, 2};
station_t FIELDS_TO_SHAWMUT = {CS29_SW3, 2};
station_t SHAWMUT_TO_FIELDS = {CS35_SW3, 2};
station_t SHAWMUT_SOUTH = {CS33_SW3, 2};
station_t SHAWMUT_NORTH = {CS30_SW3, 2};
station_t SHAWMUT_TO_ASHMONT = {CS34_SW3, 2};
station_t ASHMONT_TO_SHAWMUT = {CS32_SW3, 2};
station_t ASHMONT_SOUTH = {CS1_SW6, 1};
station_t ASHMONT_NORTH = {CS3_SW6, 1};
station_t ASHMONT_TO_CEDAR_GROVE = {CS37_SW4, 2};
station_t CEDAR_GROVE_TO_ASHMONT = {CS35_SW4, 2};
station_t CEDAR_GROVE_SOUTH = {CS36_SW4, 2};
station_t CEDAR_GROVE_NORTH = {CS39_SW4, 2};
station_t CEDAR_GROVE_TO_BUTLER = {CS37_SW5, 2};
station_t BUTLER_TO_CEDAR_GROVE = {CS38_SW5, 2};
station_t BUTLER_SOUTH = {CS39_SW6, 2};
station_t BUTLER_NORTH = {CS39_SW5, 2};
station_t BUTLER_TO_MILTON = {CS38_SW6, 2};
station_t MILTON_TO_BUTLER = {CS2_SW6, 1};
station_t MILTON_SOUTH = {CS31_SW6, 1};
station_t MILTON_NORTH = {CS6_SW6, 1};
station_t MILTON_TO_CENTRALST = {CS29_SW8, 2};
station_t CENTRALST_TO_MILTON = {CS27_SW8, 2};
station_t CENTRAL_SOUTHST = {CS30_SW8, 2};
station_t CENTRAL_NORTHST = {CS28_SW8, 2};
station_t CENTRAL_TO_VALLEY = {CS13_SW8, 2};
station_t VALLEY_TO_CENTRAL = {CS18_SW8, 2};
station_t VALLEY_SOUTH = {CS16_SW8, 2};
station_t VALLEY_NORTH = {CS32_SW8, 2};
station_t VALLEY_TO_CAPEN = {CS15_SW8, 2};
station_t CAPEN_TO_VALLEY = {CS7_SW6, 1};
station_t CAPEN_SOUTH = {CS30_SW6, 1};
station_t CAPEN_NORTH = {CS14_SW8, 2};
station_t CAPEN_TO_MATTAPAN = {CS30_SW5, 1};
station_t MATTAPAN_TO_CAPEN = {CS33_SW5, 1};
station_t MATTAPAN_SOUTH = {CS12_SW8, 2};
station_t MATTAPAN_NORTH = {CS1_SW5, 1};
station_t JFK_TO_NQUINCY = {CS5_SW4, 1};
station_t NQUINCY_TO_JFK = {CS9_SW4, 1};
station_t NQUINCY_SOUTH = {CS36_SW6, 2};
station_t NQUINCY_NORTH = {CS37_SW6, 2};
station_t NQUINCY_TO_WOLLASTON = {CS32_SW5, 2};
station_t WOLLASTON_TO_NQUINCY = {CS31_SW5, 2};
station_t WOLLASTON_SOUTH = {CS30_SW5, 2};
station_t WOLLASTON_NORTH = {CS29_SW5, 2};
station_t WOLLASTON_TO_CQUINCY = {CS31_SW4, 2};
station_t QUINCYC_TO_WOLLASTON = {CS30_SW4, 2};
station_t QUINCYC_SOUTH = {CS28_SW4, 2};
station_t QUINCYC_NORTH = {CS29_SW4, 2};
station_t QUINCYC_TO_QADAMS = {CS31_SW3, 2};
station_t QADAMS_TO_QUINCYC = {CS36_SW3, 2};
station_t QADAMS_SOUTH = {CS38_SW3, 2};
station_t QADAMS_NORTH = {CS39_SW3, 2};
station_t QADAMS_TO_BRAINTREE = {CS37_SW3, 2};
station_t BRAINTREE_TO_QADAMS = {CS39_SW2, 2};
station_t BRAINTREE_SOUTH = {CS38_SW2, 2};
station_t BRAINTREE_NORTH = {CS37_SW2, 2};

const station_t *red_line_stations[] = {
    &ALEWIFE_SOUTH,&ALEWIFE_NORTH,&ALEWIFE_TO_DAVIS,&DAVIS_TO_ALEFWIFE,&DAVIS_SOUTH,
    &DAVIS_NORTH,&DAVIS_TO_PORTER,&PORTER_TO_DAVIS,&PORTER_SOUTH,&PORTER_NORTH,&PORTER_TO_HARVARD,
    &HARVARD_TO_PORTER,&HARVARD_SOUTH,&HARVARD_NORTH,&HARVARD_TO_CENTRAL,&CENTRAL_TO_HARVARD,
    &CENTRAL_SOUTH,&CENTRAL_NORTH,&CENTRAL_TO_KENDALL,&KENDALL_TO_CENTRAL,&KENDALL_SOUTH,
    &KENDALL_NORTH,&KENDALL_TO_CHARLES,&CHARLES_TO_KENDALL,&CHARLES_SOUTH,&CHARLES_NORTH,
    &CHARLES_TO_PARKRED,&PARKRED_TO_CHARLES,&PARKRED_SOUTH,&PARKRED_NORTH,&PARKRED_TO_DOWNTOWNRED,&DOWNTOWNRED_TO_PARKRED,
    &DOWNTOWNRED_SOUTH,&DOWNTOWNRED_NORTH,&DOWNTOWNRED_TO_SOUTH,&SOUTH_TO_DOWNTOWNRED,&SOUTH_SOUTH,&SOUTH_NORTH,
    &SOUTH_TO_BROADWAY_1,&BROADWAY_TO_SOUTH_1,&SOUTH_TO_BROADWAY_2,&BROADWAY_TO_SOUTH_2,&BROADWAY_SOUTH,
    &BROADWAY_NORTH,&BROADWAY_TO_ANDREW,&ANDREW_TO_BROADWAY,&ANDREW_SOUTH,&ANDREW_NORTH,&ANDREW_TO_JFK,
    &JFK_TO_ANDREW,&JFK_SOUTH,&JFK_NORTH,&JFK_TO_SAVIN,&SAVIN_TO_JFK,&SAVIN_SOUTH,&SAVIN_NORTH,
    &SAVIN_TO_FIELDS,&FIELDS_TO_SAVIN,&FIELDS_SOUTH,&FIELDS_NORTH,&FIELDS_TO_SHAWMUT,
    &SHAWMUT_TO_FIELDS,&SHAWMUT_SOUTH,&SHAWMUT_NORTH,&SHAWMUT_TO_ASHMONT,&ASHMONT_TO_SHAWMUT,
    &ASHMONT_SOUTH,&ASHMONT_NORTH,&ASHMONT_TO_CEDAR_GROVE,&CEDAR_GROVE_TO_ASHMONT,
    &CEDAR_GROVE_SOUTH,&CEDAR_GROVE_NORTH,&CEDAR_GROVE_TO_BUTLER,&BUTLER_TO_CEDAR_GROVE,
    &BUTLER_SOUTH,&BUTLER_NORTH,&BUTLER_TO_MILTON,&MILTON_TO_BUTLER,&MILTON_SOUTH,&MILTON_NORTH,
    &MILTON_TO_CENTRALST,&CENTRALST_TO_MILTON,&CENTRAL_SOUTHST,&CENTRAL_NORTHST,&CENTRAL_TO_VALLEY,
    &VALLEY_TO_CENTRAL,&VALLEY_SOUTH,&VALLEY_NORTH,&VALLEY_TO_CAPEN,&CAPEN_TO_VALLEY,
    &CAPEN_SOUTH,&CAPEN_NORTH,&CAPEN_TO_MATTAPAN,&MATTAPAN_TO_CAPEN,&MATTAPAN_SOUTH,
    &MATTAPAN_NORTH,&JFK_TO_NQUINCY,&NQUINCY_TO_JFK,&NQUINCY_SOUTH,&NQUINCY_NORTH,
    &NQUINCY_TO_WOLLASTON,&WOLLASTON_TO_NQUINCY,&WOLLASTON_SOUTH,&WOLLASTON_NORTH,
    &WOLLASTON_TO_CQUINCY,&QUINCYC_TO_WOLLASTON,&QUINCYC_SOUTH,&QUINCYC_NORTH,
    &QUINCYC_TO_QADAMS,&QADAMS_TO_QUINCYC,&QADAMS_SOUTH,&QADAMS_NORTH,&QADAMS_TO_BRAINTREE,
    &BRAINTREE_TO_QADAMS,&BRAINTREE_SOUTH,&BRAINTREE_NORTH
};

//Blue Line
station_t WONDERLAND_EAST = {CS27_SW1, 2};
station_t WONDERLAND_WEST = {CS12_SW1, 2};
station_t WONDERLAND_TO_REVERE = {CS14_SW1, 2};
station_t REVERE_TO_WONDERLAND = {CS13_SW1, 2};
station_t REVERE_EAST = {CS33_SW2, 2};
station_t REVERE_WEST = {CS34_SW2, 2};
station_t REVERE_TO_BEACH = {CS35_SW2, 2};
station_t BEACH_TO_REVERE = {CS36_SW2, 2};
station_t BEACH_EAST = {CS27_SW3, 2};
station_t BEACH_WEST = {CS26_SW3, 2};
station_t BEACH_TO_SDOWNS = {CS25_SW3, 2};
station_t SDOWNS_TO_BEACH = {CS28_SW3, 2};
station_t SDOWNS_EAST = {CS27_SW4, 2};
station_t SDOWNS_WEST = {CS26_SW4, 2};
station_t SDOWNS_TO_OHEIGHTS = {CS23_SW5, 2};
station_t OHEIGHTS_TO_SDOWNS = {CS24_SW5, 2};
station_t OHEIGHTS_EAST = {CS26_SW5, 2};
station_t OHEIGHTS_WEST = {CS25_SW5, 2};
station_t OHEIGHTS_TO_WOODISLAND = {CS27_SW5, 2};
station_t WOODISLAND_TO_OHEIGHTS = {CS28_SW5, 2};
station_t WOODISLAND_EAST = {CS32_SW6, 2};
station_t WOODISLAND_WEST = {CS33_SW6, 2};
station_t WOODISLAND_TO_AIRPORT = {CS34_SW6, 2};
station_t AIRPORT_TO_WOODISLAND = {CS35_SW6, 2};
station_t AIRPORT_EAST = {CS8_SW1, 1};
station_t AIRPORT_WEST = {CS2_SW1, 1};
station_t AIRPORT_TO_MAV = {CS5_SW1, 1};
station_t MAV_TO_AIRPORT = {CS4_SW1, 1};
station_t MAV_EAST = {CS3_SW1, 1};
station_t MAV_WEST = {CS29_SW1, 1};
station_t MAV_TO_AQUARIUM1 = {CS30_SW1, 1};
station_t AQUARIUM_TO_MAV1 = {CS1_SW1, 1};
station_t MAV_TO_AQUARIUM2 = {CS33_SW1, 1};
station_t AQUARIUM_TO_MAV2 = {CS32_SW1, 1};
station_t AQUARIUM_EAST = {CS31_SW1, 1};
station_t AQUARIUM_WEST = {CS29_SW1, 1};
station_t AQUARIUM_TO_STATEBLUE = {CS7_SW1, 1};
station_t STATEBLUE_TO_AQUARIUM = {CS6_SW1, 1};
station_t STATEBLUE_EAST = {CS10_SW1, 1};
station_t STATEBLUE_WEST = {CS15_SW1, 1};
station_t STATEBLUE_TO_GOVCENTBLUE = {CS32_SW4, 1};
station_t GOVCENTBLUE_TO_STATE = {CS10_SW4, 1};
station_t GOVCENTBLUE_EAST = {CS1_SW4, 1};
station_t GOVCENTBLUE_WEST = {CS2_SW4, 1};
station_t GOVCENTBLUE_TO_BOW = {CS8_SW4, 1};
station_t BOW_TO_GOVCENT = {CS4_SW4, 1};
station_t BOW_EAST = {CS18_SW6, 2};
station_t BOW_WEST = {CS19_SW6, 2};



const station_t *blue_line_stations[] = {
    &WONDERLAND_EAST, &WONDERLAND_WEST, &WONDERLAND_TO_REVERE, &REVERE_TO_WONDERLAND, &REVERE_EAST,
    &REVERE_WEST, &REVERE_TO_BEACH, &BEACH_TO_REVERE, &BEACH_EAST, &BEACH_WEST, &BEACH_TO_SDOWNS, &SDOWNS_TO_BEACH,
    &SDOWNS_EAST, &SDOWNS_WEST, &SDOWNS_TO_OHEIGHTS, &OHEIGHTS_TO_SDOWNS, &OHEIGHTS_EAST, &OHEIGHTS_WEST,
    &OHEIGHTS_TO_WOODISLAND, &WOODISLAND_TO_OHEIGHTS, &WOODISLAND_EAST, &WOODISLAND_WEST, &WOODISLAND_TO_AIRPORT,
    &AIRPORT_TO_WOODISLAND, &AIRPORT_EAST, &AIRPORT_WEST, &AIRPORT_TO_MAV, &MAV_TO_AIRPORT, &MAV_EAST, &MAV_WEST,
    &MAV_TO_AQUARIUM1, &AQUARIUM_TO_MAV1, &MAV_TO_AQUARIUM2, &AQUARIUM_TO_MAV2, &AQUARIUM_EAST, &AQUARIUM_WEST,
    &AQUARIUM_TO_STATEBLUE, &STATEBLUE_TO_AQUARIUM, &STATEBLUE_EAST, &STATEBLUE_WEST, &STATEBLUE_TO_GOVCENTBLUE, &GOVCENTBLUE_TO_STATE, &GOVCENTBLUE_EAST,
    &GOVCENTBLUE_WEST, &GOVCENTBLUE_TO_BOW, &BOW_TO_GOVCENT, &BOW_EAST, &BOW_WEST
};

// Orange Line
station_t OAKGROVE_SOUTH = {CS33_SW1, 2};
station_t OAKGROVE_NORTH = {CS32_SW1, 2};
station_t OAKGROVE_TO_MALDEN = {CS31_SW1, 2};
station_t MALDEN_TO_OAKGROVE = {CS34_SW1, 2};
station_t MALDEN_SOUTH = {CS35_SW1, 2};
station_t MALDEN_NORTH = {CS36_SW1, 2};
station_t MALDEN_TO_WELLINGTON = {CS37_SW1, 2};
station_t WELLINGTON_TO_MALDEN = {CS38_SW1, 2};
station_t WELLINGTON_SOUTH = {CS39_SW1, 2};
station_t WELLINGTON_NORTH = {CS32_SW2, 2};
station_t WELLINGTON_TO_ASSEMBLY = {CS31_SW2, 2};
station_t ASSEMBLY_TO_WELLINGTON = {CS30_SW2, 2};
station_t ASSEMBLY_SOUTH = {CS23_SW3, 2};
station_t ASSEMBLY_NORTH = {CS24_SW3, 2};
station_t ASSEMBLY_TO_SULLIVAN = {CS24_SW4, 2};
station_t SULLIVAN_TO_ASSEMBLY = {CS25_SW4, 2};
station_t SULLIVAN_SOUTH = {CS21_SW5, 2};
station_t SULLIVAN_NORTH = {CS22_SW5, 2};
station_t SULLIVAN_TO_COMMUNITYCOLLEGE = {CS20_SW6, 2};
station_t COMMUNITYCOLLEGE_TO_SULLIVAN = {CS21_SW6, 2};
station_t COMMUNITYCOLLEGE_SOUTH = {CS15_SW3, 1};
station_t COMMUNITYCOLLEGE_NORTH = {CS6_SW3, 1};
station_t COMMUNITYCOLLEGE_TO_NSTATION = {CS3_SW3, 1};
station_t NSTATIONORANGE_TO_COMMUNITYCOLLEGE = {CS32_SW3, 1};
station_t NSTATIONORANGE_SOUTH = {CS7_SW3, 1};
station_t NSTATIONORANGE_NORTH = {CS9_SW3, 1};
station_t NSTATIONORANGE_TO_HAYMARKET = {CS5_SW3, 1};
station_t HAYMARKET_TO_NSTATIONORANGE = {CS30_SW3, 1};
station_t HAYMARKET_SOUTH = {CS8_SW3, 1};
station_t HAYMARKET_NORTH = {CS1_SW3, 1};
station_t HAYMARKET_TO_STATEORANGE = {CS2_SW3, 1};
station_t STATEORANGE_TO_HAYMARKET = {CS10_SW3, 1};
station_t STATEORANGE_SOUTH = {CS6_SW9, 2};
station_t STATEORANGE_NORTH = {CS7_SW9, 2};
station_t STATEORANGE_TO_DOWNTOWNCROSSINGORANGE = {CS11_SW9, 2};
station_t DOWNTOWNCROSSINGORANGE_TO_STATEORANGE = {CS22_SW9, 2};
station_t DOWNTOWNCROSSINGORANGE_SOUTH = {CS10_SW9, 2};
station_t DOWNTOWNCROSSINGORANGE_NORTH = {CS27_SW9, 2};
station_t DOWNTOWNCROSSING_TO_CHINATOWN = {CS8_SW7, 2};
station_t CHINATOWN_TO_DOWNTOWNCROSSING = {CS6_SW7, 2};
station_t CHINATOWN_SOUTH = {CS20_SW9, 2};
station_t CHINATOWN_NORTH = {CS21_SW9, 2};
station_t CHINATOWN_TO_TUFTSMEDICAL = {CS29_SW9, 2};
station_t TUFTSMEDICAL_TO_CHINATOWN = {CS25_SW9, 2};
station_t TUFTSMEDICAL_SOUTH = {CS19_SW9, 2};
station_t TUFTSMEDICAL_NORTH = {CS8_SW9, 2};
station_t TUFTSMEDICAL_TO_BACKBAY = {CS5_SW9, 2};
station_t BACKBAY_TO_TUFTSMEDICAL = {CS9_SW9, 2};
station_t BACKBAY_SOUTH = {CS33_SW3, 1};
station_t BACKBAY_NORTH = {CS31_SW3, 1};
station_t BACKBAY_TO_MASSAVE = {CS10_SW6, 1};
station_t MASSAVE_TO_BACKBAY = {CS29_SW3, 1};
station_t MASSAVE_SOUTH = {CS15_SW6, 1};
station_t MASSAVE_NORTH = {CS32_SW6, 1};
station_t MASSAVE_TO_RUGGLES = {CS6_SW2, 1};
station_t RUGGLES_TO_MASSAVE = {CS1_SW2, 1};
station_t RUGGLES_SOUTH = {CS4_SW2, 1};
station_t RUGGLES_NORTH = {CS9_SW2, 1};
station_t RUGGLES_TO_ROXBURYCROSSING = {CS7_SW2, 1};
station_t ROXBURYCROSSING_TO_RUGGLES = {CS2_SW2, 1};
station_t ROXBURYCROSSING_SOUTH = {CS5_SW2, 1};
station_t ROXBURYCROSSING_NORTH = {CS31_SW2, 1};
station_t ROXBURYCROSSING_TO_JACKSONSQ = {CS33_SW2, 1};
station_t JACKSONSQ_TO_ROXBURYCROSSING = {CS32_SW2, 1};
station_t JACKSONSQ_SOUTH = {CS15_SW2, 1};
station_t JACKSONSQ_NORTH = {CS10_SW2, 1};
station_t JACKSONSQ_TO_STONYBROOK = {CS30_SW2, 1};
station_t STONYBROOK_TO_JACKSONSQ = {CS29_SW2, 1};
station_t STONYBROOK_SOUTH = {CS8_SW2, 1};
station_t STONYBROOK_NORTH = {CS3_SW2, 1};
station_t STONYBROOK_TO_GREENST = {CS10_SW8, 2};
station_t GREENST_TO_STONYBROOK = {CS8_SW8, 2};
station_t GREENST_SOUTH = {CS31_SW8, 2};
station_t GREENST_NORTH = {CS17_SW8, 2};
station_t GREENST_TO_FORESTHILLS = {CS33_SW6, 1};
station_t FORESTHILLS_TO_GREENST = {CS1_SW8, 2};
station_t FORESTHILLS_SOUTH = {CS36_SW8, 2};
station_t FORESTHILLS_NORTH = {CS34_SW8, 2};


const station_t *orange_line_stations[] = {
    &OAKGROVE_SOUTH, &OAKGROVE_NORTH, &OAKGROVE_TO_MALDEN, &MALDEN_TO_OAKGROVE,
    &MALDEN_SOUTH, &MALDEN_NORTH, &MALDEN_TO_WELLINGTON, &WELLINGTON_TO_MALDEN, &WELLINGTON_SOUTH,
    &WELLINGTON_NORTH, &WELLINGTON_TO_ASSEMBLY, &ASSEMBLY_TO_WELLINGTON, &ASSEMBLY_SOUTH,
    &ASSEMBLY_NORTH, &ASSEMBLY_TO_SULLIVAN, &SULLIVAN_TO_ASSEMBLY, &SULLIVAN_SOUTH, &SULLIVAN_NORTH,
    &SULLIVAN_TO_COMMUNITYCOLLEGE, &COMMUNITYCOLLEGE_TO_SULLIVAN, &COMMUNITYCOLLEGE_SOUTH, &COMMUNITYCOLLEGE_NORTH,
    &COMMUNITYCOLLEGE_TO_NSTATION, &NSTATIONORANGE_TO_COMMUNITYCOLLEGE, &NSTATIONORANGE_SOUTH, &NSTATIONORANGE_NORTH,
    &NSTATIONORANGE_TO_HAYMARKET, &HAYMARKET_TO_NSTATIONORANGE, &HAYMARKET_SOUTH, &HAYMARKET_NORTH, &HAYMARKET_TO_STATEORANGE,
    &STATEORANGE_TO_HAYMARKET, &STATEORANGE_SOUTH, &STATEORANGE_NORTH, &STATEORANGE_TO_DOWNTOWNCROSSINGORANGE,
    &DOWNTOWNCROSSINGORANGE_TO_STATEORANGE, &DOWNTOWNCROSSINGORANGE_SOUTH, &DOWNTOWNCROSSINGORANGE_NORTH,
    &DOWNTOWNCROSSING_TO_CHINATOWN, &CHINATOWN_TO_DOWNTOWNCROSSING, &CHINATOWN_SOUTH, &CHINATOWN_NORTH, &CHINATOWN_TO_TUFTSMEDICAL,
    &TUFTSMEDICAL_TO_CHINATOWN, &TUFTSMEDICAL_SOUTH, &TUFTSMEDICAL_NORTH, &TUFTSMEDICAL_TO_BACKBAY, &BACKBAY_TO_TUFTSMEDICAL,
    &BACKBAY_SOUTH, &BACKBAY_NORTH, &BACKBAY_TO_MASSAVE, &MASSAVE_TO_BACKBAY, &MASSAVE_SOUTH, &MASSAVE_NORTH, &MASSAVE_TO_RUGGLES,
    &RUGGLES_TO_MASSAVE, &RUGGLES_SOUTH, &RUGGLES_NORTH, &RUGGLES_TO_ROXBURYCROSSING, &ROXBURYCROSSING_TO_RUGGLES, &ROXBURYCROSSING_SOUTH,
    &ROXBURYCROSSING_NORTH, &ROXBURYCROSSING_TO_JACKSONSQ, &JACKSONSQ_TO_ROXBURYCROSSING, &JACKSONSQ_SOUTH, &JACKSONSQ_NORTH, &JACKSONSQ_TO_STONYBROOK,
    &STONYBROOK_TO_JACKSONSQ, &STONYBROOK_SOUTH, &STONYBROOK_NORTH, &STONYBROOK_TO_GREENST, &GREENST_TO_STONYBROOK,
    &GREENST_SOUTH, &GREENST_NORTH, &GREENST_TO_FORESTHILLS, &FORESTHILLS_TO_GREENST, &FORESTHILLS_SOUTH, &FORESTHILLS_NORTH
};


//need to add parameters for i2c device list so that the function knows which device it is picking.
uint32_t setStation(const station_t *station, int amplitude, i2c_master_dev_handle_t U1, i2c_master_dev_handle_t U2){

    uint32_t result = 0;
    if(station->chip==1){
        result = writeLED(station->addr, amplitude, U1);
    }

    else if (station->chip==2)
    {
        result = writeLED(station->addr, amplitude, U2);
    }
    else{
        result = 0;
    }
    return result;
    

}

uint32_t clearStation(const station_t *station, i2c_master_dev_handle_t U1, i2c_master_dev_handle_t U2){

    uint32_t result = 0;
    if(station->chip==1){
        result = writeLED(station->addr, 00, U1);
    }

    else if (station->chip==2)
    {
        result = writeLED(station->addr, 00, U2);
    }
    else{
        result=0;
    }
    return result;
    

}









