#include "driver/i2c_master.h"
#include "freertos/FreeRTOS.h"
#include "s31fl3741a.h"
#include "station_map.h"

//alankilian@gmail.com help with T api

//Red Line
station_t ALEWIFE_SOUTH     = {CS28_SW1, 2};
station_t ALEWIFE_NORTH     = {CS30_SW1, 2};
station_t ALEWIFE_TO_DAVIS  = {CS18_SW1, 2};
station_t DAVIS_TO_ALEFWIFE = {CS17_SW1, 2};
station_t DAVIS_SOUTH       = {CS22_SW2, 2};
station_t DAVIS_NORTH       = {CS23_SW2, 2};
station_t DAVIS_TO_PORTER   = {CS25_SW2, 2};
station_t PORTER_TO_DAVIS   = {CS24_SW2, 2};
station_t PORTER_SOUTH      = {CS16_SW6, 1};
station_t PORTER_NORTH      = {CS29_SW6, 1};
station_t PORTER_TO_HARVARD = {CS29_SW5, 1};
station_t HARVARD_TO_PORTER = {CS18_SW3, 2};
station_t HARVARD_SOUTH = {CS15_SW3, 2};
station_t HARVARD_NORTH = {CS17_SW3, 2};
station_t HARVARD_TO_CENTRAL = {CS16_SW3, 2};
station_t CENTRAL_TO_HARVARD = {CS13_SW4, 2};
station_t CENTRAL_SOUTH = {CS15_SW4, 2};
station_t CENTRAL_NORTH = {CS14_SW4, 2};
station_t CENTRAL_TO_KENDALL = {CS13_SW5, 2};
station_t KENDALL_TO_CENTRAL = {CS14_SW5, 2};
station_t KENDALL_SOUTH = {CS16_SW5, 2};
station_t KENDALL_NORTH = {CS15_SW5, 2};
station_t KENDALL_TO_CHARLES = {CS24_SW6, 2};
station_t CHARLES_TO_KENDALL = {CS25_SW6, 2};
station_t CHARLES_SOUTH = {CS22_SW6, 2};
station_t CHARLES_NORTH = {CS23_SW6, 2};
station_t CHARLES_TO_PARKRED = {CS35_SW9, 2};
station_t PARKRED_TO_CHARLES = {CS33_SW9, 2};
station_t PARKRED_SOUTH = {CS39_SW9, 2};
station_t PARKRED_NORTH = {CS37_SW9, 2};
station_t PARKRED_TO_DOWNTOWNRED = {CS32_SW9, 2};
station_t DOWNTOWNRED_TO_PARKRED = {CS28_SW9, 2};
station_t DOWNTOWNRED_SOUTH = {CS34_SW9, 2};
station_t DOWNTOWNRED_NORTH = {CS18_SW9, 2};
station_t DOWNTOWNRED_TO_SOUTH = {CS17_SW9, 2};
station_t SOUTH_TO_DOWNTOWNRED = {CS30_SW9, 2};
station_t SOUTH_SOUTH = {CS14_SW7, 2};
station_t SOUTH_NORTH = {CS4_SW7, 2};
station_t SOUTH_TO_BROADWAY_1 = {CS10_SW7, 2};
station_t BROADWAY_TO_SOUTH_1 = {CS34_SW7, 2};
station_t SOUTH_TO_BROADWAY_2 = {CS38_SW7, 2};
station_t BROADWAY_TO_SOUTH_2 = {CS39_SW7, 2};
station_t BROADWAY_SOUTH = {CS32_SW7, 2};
station_t BROADWAY_NORTH = {CS5_SW7, 2};
station_t BROADWAY_TO_ANDREW = {CS4_SW3, 1};
station_t ANDREW_TO_BROADWAY = {CS3_SW4, 1};
station_t ANDREW_SOUTH = {CS6_SW4, 1};
station_t ANDREW_NORTH = {CS15_SW4, 1};
station_t ANDREW_TO_JFK = {CS33_SW4, 1};
station_t JFK_TO_ANDREW = {CS29_SW4, 1};
station_t JFK_SOUTH = {CS7_SW4, 1};
station_t JFK_NORTH = {CS31_SW4, 1};
station_t JFK_TO_SAVIN = {CS36_SW5, 2};
station_t SAVIN_TO_JFK = {CS35_SW5, 2};
station_t SAVIN_SOUTH = {CS34_SW5, 2};
station_t SAVIN_NORTH = {CS33_SW5, 2};
station_t SAVIN_TO_FIELDS = {CS38_SW4, 2};
station_t FIELDS_TO_SAVIN = {CS33_SW4, 2};
station_t FIELDS_SOUTH = {CS32_SW4, 2};
station_t FIELDS_NORTH = {CS34_SW4, 2};
station_t FIELDS_TO_SHAWMUT = {CS29_SW3, 2};
station_t SHAWMUT_TO_FIELDS = {CS35_SW3, 2};
station_t SHAWMUT_SOUTH = {CS33_SW3, 2};
station_t SHAWMUT_NORTH = {CS30_SW3, 2};
station_t SHAWMUT_TO_ASHMONT = {CS34_SW3, 2};
station_t ASHMONT_TO_SHAWMUT = {CS32_SW3, 2};
station_t ASHMONT_SOUTH = {CS1_SW6, 1};
station_t ASHMONT_NORTH = {CS3_SW6, 1};
station_t ASHMONT_TO_CEDAR_GROVE = {CS37_SW4, 2};
station_t CEDAR_GROVE_TO_ASHMONT = {CS35_SW4, 2};
station_t CEDAR_GROVE_SOUTH = {CS36_SW4, 2};
station_t CEDAR_GROVE_NORTH = {CS39_SW4, 2};
station_t CEDAR_GROVE_TO_BUTLER = {CS37_SW5, 2};
station_t BUTLER_TO_CEDAR_GROVE = {CS38_SW5, 2};
station_t BUTLER_SOUTH = {CS39_SW6, 2};
station_t BUTLER_NORTH = {CS39_SW5, 2};
station_t BUTLER_TO_MILTON = {CS38_SW6, 2};
station_t MILTON_TO_BUTLER = {CS2_SW6, 1};
station_t MILTON_SOUTH = {CS31_SW6, 1};
station_t MILTON_NORTH = {CS6_SW6, 1};
station_t MILTON_TO_CENTRALST = {CS29_SW8, 2};
station_t CENTRALST_TO_MILTON = {CS27_SW8, 2};
station_t CENTRALST_SOUTH = {CS30_SW8, 2};
station_t CENTRALST_NORTH = {CS28_SW8, 2};
station_t CENTRAL_TO_VALLEY = {CS13_SW8, 2};
station_t VALLEY_TO_CENTRAL = {CS18_SW8, 2};
station_t VALLEY_SOUTH = {CS16_SW8, 2};
station_t VALLEY_NORTH = {CS32_SW8, 2};
station_t VALLEY_TO_CAPEN = {CS15_SW8, 2};
station_t CAPEN_TO_VALLEY = {CS7_SW6, 1};
station_t CAPEN_SOUTH = {CS30_SW6, 1};
station_t CAPEN_NORTH = {CS14_SW8, 2};
station_t CAPEN_TO_MATTAPAN = {CS30_SW5, 1};
station_t MATTAPAN_TO_CAPEN = {CS33_SW5, 1};
station_t MATTAPAN_SOUTH = {CS12_SW8, 2};
station_t MATTAPAN_NORTH = {CS1_SW5, 1};
station_t JFK_TO_NQUINCY = {CS5_SW4, 1};
station_t NQUINCY_TO_JFK = {CS9_SW4, 1};
station_t NQUINCY_SOUTH = {CS36_SW6, 2};
station_t NQUINCY_NORTH = {CS37_SW6, 2};
station_t NQUINCY_TO_WOLLASTON = {CS32_SW5, 2};
station_t WOLLASTON_TO_NQUINCY = {CS31_SW5, 2};
station_t WOLLASTON_SOUTH = {CS30_SW5, 2};
station_t WOLLASTON_NORTH = {CS29_SW5, 2};
station_t WOLLASTON_TO_CQUINCY = {CS31_SW4, 2};
station_t QUINCYC_TO_WOLLASTON = {CS30_SW4, 2};
station_t QUINCYC_SOUTH = {CS28_SW4, 2};
station_t QUINCYC_NORTH = {CS29_SW4, 2};
station_t QUINCYC_TO_QADAMS = {CS31_SW3, 2};
station_t QADAMS_TO_QUINCYC = {CS36_SW3, 2};
station_t QADAMS_SOUTH = {CS38_SW3, 2};
station_t QADAMS_NORTH = {CS39_SW3, 2};
station_t QADAMS_TO_BRAINTREE = {CS37_SW3, 2};
station_t BRAINTREE_TO_QADAMS = {CS39_SW2, 2};
station_t BRAINTREE_SOUTH = {CS38_SW2, 2};
station_t BRAINTREE_NORTH = {CS37_SW2, 2};

const station_t *red_line_stations[] = {
    &ALEWIFE_SOUTH,&ALEWIFE_TO_DAVIS,&DAVIS_SOUTH,
    &DAVIS_TO_PORTER,&PORTER_SOUTH,&PORTER_TO_HARVARD,
    &HARVARD_SOUTH,&HARVARD_TO_CENTRAL,
    &CENTRAL_SOUTH,&CENTRAL_TO_KENDALL,&KENDALL_SOUTH,
    &KENDALL_TO_CHARLES,&CHARLES_SOUTH,
    &CHARLES_TO_PARKRED,&PARKRED_SOUTH,&PARKRED_TO_DOWNTOWNRED,
    &DOWNTOWNRED_SOUTH,&DOWNTOWNRED_TO_SOUTH,&SOUTH_SOUTH,
    &SOUTH_TO_BROADWAY_1,&SOUTH_TO_BROADWAY_2,&BROADWAY_SOUTH,
    &BROADWAY_TO_ANDREW,&ANDREW_SOUTH,&ANDREW_TO_JFK,
    &JFK_SOUTH,&JFK_TO_SAVIN,&SAVIN_SOUTH,
    &SAVIN_TO_FIELDS,&FIELDS_SOUTH,&FIELDS_TO_SHAWMUT,
    &SHAWMUT_SOUTH,&SHAWMUT_TO_ASHMONT,
    &ASHMONT_SOUTH,&ASHMONT_TO_CEDAR_GROVE,
    &CEDAR_GROVE_SOUTH,&CEDAR_GROVE_TO_BUTLER,
    &BUTLER_SOUTH,&BUTLER_TO_MILTON,&MILTON_SOUTH,
    &MILTON_TO_CENTRALST,&CENTRALST_SOUTH,&CENTRAL_TO_VALLEY,
    &VALLEY_SOUTH,&VALLEY_TO_CAPEN,
    &CAPEN_SOUTH,&CAPEN_TO_MATTAPAN,&MATTAPAN_SOUTH,
    &JFK_TO_NQUINCY,&NQUINCY_SOUTH,
    &NQUINCY_TO_WOLLASTON,&WOLLASTON_SOUTH,
    &WOLLASTON_TO_CQUINCY,&QUINCYC_SOUTH,
    &QUINCYC_TO_QADAMS,&QADAMS_SOUTH,&QADAMS_TO_BRAINTREE,
    &BRAINTREE_SOUTH,

    &ALEWIFE_NORTH,&DAVIS_TO_ALEFWIFE,&DAVIS_NORTH,&PORTER_TO_DAVIS,&PORTER_NORTH,&HARVARD_TO_PORTER,
    &HARVARD_NORTH,&CENTRAL_TO_HARVARD,&CENTRAL_NORTH,&KENDALL_TO_CENTRAL,&KENDALL_NORTH,&CHARLES_TO_KENDALL,
    &CHARLES_NORTH,&PARKRED_TO_CHARLES,&PARKRED_NORTH,&DOWNTOWNRED_TO_PARKRED,&DOWNTOWNRED_NORTH,&SOUTH_TO_DOWNTOWNRED,
    &SOUTH_NORTH,&BROADWAY_TO_SOUTH_1,&BROADWAY_TO_SOUTH_2,&BROADWAY_NORTH,&ANDREW_TO_BROADWAY,&ANDREW_NORTH,&JFK_TO_ANDREW,
    &JFK_NORTH,&SAVIN_TO_JFK,&SAVIN_NORTH,&FIELDS_TO_SAVIN,&FIELDS_NORTH,&SHAWMUT_TO_FIELDS,&SHAWMUT_NORTH,&ASHMONT_TO_SHAWMUT,
    &ASHMONT_NORTH,&CEDAR_GROVE_TO_ASHMONT,&CEDAR_GROVE_NORTH,&BUTLER_TO_CEDAR_GROVE,&BUTLER_NORTH,&MILTON_TO_BUTLER,
    &MILTON_NORTH,&CENTRALST_TO_MILTON,&CENTRALST_NORTH,&VALLEY_TO_CENTRAL,&VALLEY_NORTH,&CAPEN_TO_VALLEY,&CAPEN_NORTH,
    &MATTAPAN_TO_CAPEN,&MATTAPAN_NORTH,&NQUINCY_TO_JFK,&NQUINCY_NORTH,&WOLLASTON_TO_NQUINCY,&WOLLASTON_NORTH,
    &QUINCYC_TO_WOLLASTON,&QUINCYC_NORTH,&QADAMS_TO_QUINCYC,&QADAMS_NORTH,&BRAINTREE_TO_QADAMS,&BRAINTREE_NORTH

};

//Blue Line
station_t WONDERLAND_EAST = {CS27_SW1, 2};
station_t WONDERLAND_WEST = {CS12_SW1, 2};
station_t WONDERLAND_TO_REVERE = {CS14_SW1, 2};
station_t REVERE_TO_WONDERLAND = {CS13_SW1, 2};
station_t REVERE_EAST = {CS33_SW2, 2};
station_t REVERE_WEST = {CS34_SW2, 2};
station_t REVERE_TO_BEACH = {CS35_SW2, 2};
station_t BEACH_TO_REVERE = {CS36_SW2, 2};
station_t BEACH_EAST = {CS27_SW3, 2};
station_t BEACH_WEST = {CS26_SW3, 2};
station_t BEACH_TO_SDOWNS = {CS25_SW3, 2};
station_t SDOWNS_TO_BEACH = {CS28_SW3, 2};
station_t SDOWNS_EAST = {CS27_SW4, 2};
station_t SDOWNS_WEST = {CS26_SW4, 2};
station_t SDOWNS_TO_OHEIGHTS = {CS23_SW5, 2};
station_t OHEIGHTS_TO_SDOWNS = {CS24_SW5, 2};
station_t OHEIGHTS_EAST = {CS26_SW5, 2};
station_t OHEIGHTS_WEST = {CS25_SW5, 2};
station_t OHEIGHTS_TO_WOODISLAND = {CS27_SW5, 2};
station_t WOODISLAND_TO_OHEIGHTS = {CS28_SW5, 2};
station_t WOODISLAND_EAST = {CS32_SW6, 2};
station_t WOODISLAND_WEST = {CS33_SW6, 2};
station_t WOODISLAND_TO_AIRPORT = {CS34_SW6, 2};
station_t AIRPORT_TO_WOODISLAND = {CS35_SW6, 2};
station_t AIRPORT_EAST = {CS8_SW1, 1};
station_t AIRPORT_WEST = {CS2_SW1, 1};
station_t AIRPORT_TO_MAV = {CS5_SW1, 1};
station_t MAV_TO_AIRPORT = {CS4_SW1, 1};
station_t MAV_EAST = {CS3_SW1, 1};
station_t MAV_WEST = {CS29_SW1, 1};
station_t MAV_TO_AQUARIUM1 = {CS30_SW1, 1};
station_t AQUARIUM_TO_MAV1 = {CS1_SW1, 1};
station_t MAV_TO_AQUARIUM2 = {CS33_SW1, 1};
station_t AQUARIUM_TO_MAV2 = {CS32_SW1, 1};
station_t AQUARIUM_EAST = {CS31_SW1, 1};
station_t AQUARIUM_WEST = {CS29_SW1, 1};
station_t AQUARIUM_TO_STATEBLUE = {CS7_SW1, 1};
station_t STATEBLUE_TO_AQUARIUM = {CS6_SW1, 1};
station_t STATEBLUE_EAST = {CS10_SW1, 1};
station_t STATEBLUE_WEST = {CS15_SW1, 1};
station_t STATEBLUE_TO_GOVCENTBLUE = {CS32_SW4, 1};
station_t GOVCENTBLUE_TO_STATE = {CS10_SW4, 1};
station_t GOVCENTBLUE_EAST = {CS1_SW4, 1};
station_t GOVCENTBLUE_WEST = {CS2_SW4, 1};
station_t GOVCENTBLUE_TO_BOW = {CS8_SW4, 1};
station_t BOW_TO_GOVCENT = {CS4_SW4, 1};
station_t BOW_EAST = {CS18_SW6, 2};
station_t BOW_WEST = {CS19_SW6, 2};



const station_t *blue_line_stations[] = {
    &WONDERLAND_EAST, &WONDERLAND_WEST, &WONDERLAND_TO_REVERE, &REVERE_TO_WONDERLAND, &REVERE_EAST,
    &REVERE_WEST, &REVERE_TO_BEACH, &BEACH_TO_REVERE, &BEACH_EAST, &BEACH_WEST, &BEACH_TO_SDOWNS, &SDOWNS_TO_BEACH,
    &SDOWNS_EAST, &SDOWNS_WEST, &SDOWNS_TO_OHEIGHTS, &OHEIGHTS_TO_SDOWNS, &OHEIGHTS_EAST, &OHEIGHTS_WEST,
    &OHEIGHTS_TO_WOODISLAND, &WOODISLAND_TO_OHEIGHTS, &WOODISLAND_EAST, &WOODISLAND_WEST, &WOODISLAND_TO_AIRPORT,
    &AIRPORT_TO_WOODISLAND, &AIRPORT_EAST, &AIRPORT_WEST, &AIRPORT_TO_MAV, &MAV_TO_AIRPORT, &MAV_EAST, &MAV_WEST,
    &MAV_TO_AQUARIUM1, &AQUARIUM_TO_MAV1, &MAV_TO_AQUARIUM2, &AQUARIUM_TO_MAV2, &AQUARIUM_EAST, &AQUARIUM_WEST,
    &AQUARIUM_TO_STATEBLUE, &STATEBLUE_TO_AQUARIUM, &STATEBLUE_EAST, &STATEBLUE_WEST, &STATEBLUE_TO_GOVCENTBLUE, &GOVCENTBLUE_TO_STATE, &GOVCENTBLUE_EAST,
    &GOVCENTBLUE_WEST, &GOVCENTBLUE_TO_BOW, &BOW_TO_GOVCENT, &BOW_EAST, &BOW_WEST
};

// Orange Line
station_t OAKGROVE_SOUTH = {CS33_SW1, 2};
station_t OAKGROVE_NORTH = {CS32_SW1, 2};
station_t OAKGROVE_TO_MALDEN = {CS31_SW1, 2};
station_t MALDEN_TO_OAKGROVE = {CS34_SW1, 2};
station_t MALDEN_SOUTH = {CS35_SW1, 2};
station_t MALDEN_NORTH = {CS36_SW1, 2};
station_t MALDEN_TO_WELLINGTON = {CS37_SW1, 2};
station_t WELLINGTON_TO_MALDEN = {CS38_SW1, 2};
station_t WELLINGTON_SOUTH = {CS39_SW1, 2};
station_t WELLINGTON_NORTH = {CS32_SW2, 2};
station_t WELLINGTON_TO_ASSEMBLY = {CS31_SW2, 2};
station_t ASSEMBLY_TO_WELLINGTON = {CS30_SW2, 2};
station_t ASSEMBLY_SOUTH = {CS23_SW3, 2};
station_t ASSEMBLY_NORTH = {CS24_SW3, 2};
station_t ASSEMBLY_TO_SULLIVAN = {CS24_SW4, 2};
station_t SULLIVAN_TO_ASSEMBLY = {CS25_SW4, 2};
station_t SULLIVAN_SOUTH = {CS21_SW5, 2};
station_t SULLIVAN_NORTH = {CS22_SW5, 2};
station_t SULLIVAN_TO_COMMUNITYCOLLEGE = {CS20_SW6, 2};
station_t COMMUNITYCOLLEGE_TO_SULLIVAN = {CS21_SW6, 2};
station_t COMMUNITYCOLLEGE_SOUTH = {CS15_SW3, 1};
station_t COMMUNITYCOLLEGE_NORTH = {CS6_SW3, 1};
station_t COMMUNITYCOLLEGE_TO_NSTATION = {CS3_SW3, 1};
station_t NSTATIONORANGE_TO_COMMUNITYCOLLEGE = {CS32_SW3, 1};
station_t NSTATIONORANGE_SOUTH = {CS7_SW3, 1};
station_t NSTATIONORANGE_NORTH = {CS9_SW3, 1};
station_t NSTATIONORANGE_TO_HAYMARKETORANGE = {CS5_SW3, 1};
station_t HAYMARKETORANGE_TO_NSTATIONORANGE = {CS30_SW3, 1};
station_t HAYMARKETORANGE_SOUTH = {CS8_SW3, 1};
station_t HAYMARKETORANGE_NORTH = {CS1_SW3, 1};
station_t HAYMARKETORANGE_TO_STATEORANGE = {CS2_SW3, 1};
station_t STATEORANGE_TO_HAYMARKETORANGE = {CS10_SW3, 1};
station_t STATEORANGE_SOUTH = {CS6_SW9, 2};
station_t STATEORANGE_NORTH = {CS7_SW9, 2};
station_t STATEORANGE_TO_DOWNTOWNCROSSINGORANGE = {CS11_SW9, 2};
station_t DOWNTOWNCROSSINGORANGE_TO_STATEORANGE = {CS22_SW9, 2};
station_t DOWNTOWNCROSSINGORANGE_SOUTH = {CS10_SW9, 2};
station_t DOWNTOWNCROSSINGORANGE_NORTH = {CS27_SW9, 2};
station_t DOWNTOWNCROSSING_TO_CHINATOWN = {CS8_SW7, 2};
station_t CHINATOWN_TO_DOWNTOWNCROSSING = {CS6_SW7, 2};
station_t CHINATOWN_SOUTH = {CS20_SW9, 2};
station_t CHINATOWN_NORTH = {CS21_SW9, 2};
station_t CHINATOWN_TO_TUFTSMEDICAL = {CS29_SW9, 2};
station_t TUFTSMEDICAL_TO_CHINATOWN = {CS25_SW9, 2};
station_t TUFTSMEDICAL_SOUTH = {CS19_SW9, 2};
station_t TUFTSMEDICAL_NORTH = {CS8_SW9, 2};
station_t TUFTSMEDICAL_TO_BACKBAY = {CS5_SW9, 2};
station_t BACKBAY_TO_TUFTSMEDICAL = {CS9_SW9, 2};
station_t BACKBAY_SOUTH = {CS33_SW3, 1};
station_t BACKBAY_NORTH = {CS31_SW3, 1};
station_t BACKBAY_TO_MASSAVE = {CS10_SW6, 1};
station_t MASSAVE_TO_BACKBAY = {CS29_SW3, 1};
station_t MASSAVE_SOUTH = {CS15_SW6, 1};
station_t MASSAVE_NORTH = {CS32_SW6, 1};
station_t MASSAVE_TO_RUGGLES = {CS6_SW2, 1};
station_t RUGGLES_TO_MASSAVE = {CS1_SW2, 1};
station_t RUGGLES_SOUTH = {CS4_SW2, 1};
station_t RUGGLES_NORTH = {CS9_SW2, 1};
station_t RUGGLES_TO_ROXBURYCROSSING = {CS7_SW2, 1};
station_t ROXBURYCROSSING_TO_RUGGLES = {CS2_SW2, 1};
station_t ROXBURYCROSSING_SOUTH = {CS5_SW2, 1};
station_t ROXBURYCROSSING_NORTH = {CS31_SW2, 1};
station_t ROXBURYCROSSING_TO_JACKSONSQ = {CS33_SW2, 1};
station_t JACKSONSQ_TO_ROXBURYCROSSING = {CS32_SW2, 1};
station_t JACKSONSQ_SOUTH = {CS15_SW2, 1};
station_t JACKSONSQ_NORTH = {CS10_SW2, 1};
station_t JACKSONSQ_TO_STONYBROOK = {CS30_SW2, 1};
station_t STONYBROOK_TO_JACKSONSQ = {CS29_SW2, 1};
station_t STONYBROOK_SOUTH = {CS8_SW2, 1};
station_t STONYBROOK_NORTH = {CS3_SW2, 1};
station_t STONYBROOK_TO_GREENST = {CS10_SW8, 2};
station_t GREENST_TO_STONYBROOK = {CS8_SW8, 2};
station_t GREENST_SOUTH = {CS31_SW8, 2};
station_t GREENST_NORTH = {CS17_SW8, 2};
station_t GREENST_TO_FORESTHILLS = {CS33_SW6, 1};
station_t FORESTHILLS_TO_GREENST = {CS1_SW8, 2};
station_t FORESTHILLS_SOUTH = {CS36_SW8, 2};
station_t FORESTHILLS_NORTH = {CS34_SW8, 2};


const station_t *orange_line_stations[] = {
    &OAKGROVE_SOUTH, &OAKGROVE_NORTH, &OAKGROVE_TO_MALDEN, &MALDEN_TO_OAKGROVE,
    &MALDEN_SOUTH, &MALDEN_NORTH, &MALDEN_TO_WELLINGTON, &WELLINGTON_TO_MALDEN, &WELLINGTON_SOUTH,
    &WELLINGTON_NORTH, &WELLINGTON_TO_ASSEMBLY, &ASSEMBLY_TO_WELLINGTON, &ASSEMBLY_SOUTH,
    &ASSEMBLY_NORTH, &ASSEMBLY_TO_SULLIVAN, &SULLIVAN_TO_ASSEMBLY, &SULLIVAN_SOUTH, &SULLIVAN_NORTH,
    &SULLIVAN_TO_COMMUNITYCOLLEGE, &COMMUNITYCOLLEGE_TO_SULLIVAN, &COMMUNITYCOLLEGE_SOUTH, &COMMUNITYCOLLEGE_NORTH,
    &COMMUNITYCOLLEGE_TO_NSTATION, &NSTATIONORANGE_TO_COMMUNITYCOLLEGE, &NSTATIONORANGE_SOUTH, &NSTATIONORANGE_NORTH,
    &NSTATIONORANGE_TO_HAYMARKETORANGE, &HAYMARKETORANGE_TO_NSTATIONORANGE, &HAYMARKETORANGE_SOUTH, &HAYMARKETORANGE_NORTH, &HAYMARKETORANGE_TO_STATEORANGE,
    &STATEORANGE_TO_HAYMARKETORANGE, &STATEORANGE_SOUTH, &STATEORANGE_NORTH, &STATEORANGE_TO_DOWNTOWNCROSSINGORANGE,
    &DOWNTOWNCROSSINGORANGE_TO_STATEORANGE, &DOWNTOWNCROSSINGORANGE_SOUTH, &DOWNTOWNCROSSINGORANGE_NORTH,
    &DOWNTOWNCROSSING_TO_CHINATOWN, &CHINATOWN_TO_DOWNTOWNCROSSING, &CHINATOWN_SOUTH, &CHINATOWN_NORTH, &CHINATOWN_TO_TUFTSMEDICAL,
    &TUFTSMEDICAL_TO_CHINATOWN, &TUFTSMEDICAL_SOUTH, &TUFTSMEDICAL_NORTH, &TUFTSMEDICAL_TO_BACKBAY, &BACKBAY_TO_TUFTSMEDICAL,
    &BACKBAY_SOUTH, &BACKBAY_NORTH, &BACKBAY_TO_MASSAVE, &MASSAVE_TO_BACKBAY, &MASSAVE_SOUTH, &MASSAVE_NORTH, &MASSAVE_TO_RUGGLES,
    &RUGGLES_TO_MASSAVE, &RUGGLES_SOUTH, &RUGGLES_NORTH, &RUGGLES_TO_ROXBURYCROSSING, &ROXBURYCROSSING_TO_RUGGLES, &ROXBURYCROSSING_SOUTH,
    &ROXBURYCROSSING_NORTH, &ROXBURYCROSSING_TO_JACKSONSQ, &JACKSONSQ_TO_ROXBURYCROSSING, &JACKSONSQ_SOUTH, &JACKSONSQ_NORTH, &JACKSONSQ_TO_STONYBROOK,
    &STONYBROOK_TO_JACKSONSQ, &STONYBROOK_SOUTH, &STONYBROOK_NORTH, &STONYBROOK_TO_GREENST, &GREENST_TO_STONYBROOK,
    &GREENST_SOUTH, &GREENST_NORTH, &GREENST_TO_FORESTHILLS, &FORESTHILLS_TO_GREENST, &FORESTHILLS_SOUTH, &FORESTHILLS_NORTH
};

// Green Line - Medford/Tufts Branch
station_t MEDFORD_TUFTS_SOUTH = {CS10_SW1, 2};
station_t MEDFORD_TUFTS_NORTH = {CS11_SW1, 2};
station_t MEDFORD_TUFTS_TO_BALL_SQUARE = {CS15_SW1, 2};
station_t BALL_SQUARE_TO_MEDFORD_TUFTS = {CS16_SW1, 2};
station_t BALL_SQUARE_SOUTH = {CS27_SW2, 2};
station_t BALL_SQUARE_NORTH = {CS26_SW2, 2};
station_t BALL_SQUARE_TO_MAGOUN_SQUARE = {CS28_SW2, 2};
station_t MAGOUN_SQUARE_TO_BALL_SQUARE = {CS29_SW2, 2};
station_t MAGOUN_SQUARE_SOUTH = {CS19_SW3, 2};
station_t MAGOUN_SQUARE_NORTH = {CS20_SW3, 2};
station_t MAGOUN_SQUARE_TO_GILMAN_SQUARE = {CS22_SW3, 2};
station_t GILMAN_SQUARE_TO_MAGOUN_SQUARE = {CS21_SW3, 2};
station_t GILMAN_SQUARE_SOUTH = {CS19_SW4, 2};
station_t GILMAN_SQUARE_NORTH = {CS18_SW4, 2};
station_t GILMAN_SQUARE_TO_EAST_SOMERVILLE = {CS21_SW4, 2};
station_t EAST_SOMERVILLE_TO_GILMAN_SQUARE = {CS20_SW4, 2};
station_t EAST_SOMERVILLE_SOUTH = {CS5_SW6, 1};
station_t EAST_SOMERVILLE_NORTH = {CS22_SW4, 2};
station_t EAST_SOMERVILLE_TO_LECHMERE = {CS8_SW6, 1};
station_t LECHMERE_TO_EAST_SOMERVILLE = {CS23_SW4, 2};
station_t LECHMERE_SOUTH = {CS17_SW5, 2};
station_t LECHMERE_NORTH = {CS18_SW5, 2};
station_t UNION_SOUTH = {CS16_SW4, 2};
station_t UNION_NORTH = {CS17_SW4, 2};
station_t UNION_TO_LECHMERE = {CS4_SW6, 1};
station_t LECHMERE_TO_UNION = {CS9_SW6, 1};
station_t LECHMERE_TO_SCIENCEPARK = {CS19_SW5, 2};
station_t SCIENCEPARK_TO_LECHMERE = {CS20_SW5, 2};
station_t SCIENCEPARK_SOUTH = {CS17_SW6, 2};
station_t SCIENCEPARK_NORTH = {CS16_SW6, 2};
station_t SCIENCEPARK_TO_NSTATIONGREEN = {CS9_SW7, 2};
station_t NSTATIONGREEN_TO_SCIENCEPARK = {CS12_SW7, 2};
station_t NSTATIONGREEN_SOUTH = {CS15_SW7, 2};
station_t NSTATIONGREEN_NORTH = {CS17_SW7, 2};
station_t NSTATIONGREEN_TO_HAYMARKETGREEN = {CS18_SW7, 2};
station_t HAYMARKETGREEN_TO_NSTATIONGREEN = {CS20_SW7, 2};
station_t HAYMARKETGREEN_SOUTH = {CS21_SW7, 2};
station_t HAYMARKETGREEN_NORTH = {CS22_SW7, 2};
station_t HAYMARKETGREEN_TO_GOVCENTGREEN = {CS16_SW7, 2};
station_t GOVCENTGREEN_TO_HAYMARKETGREEN = {CS19_SW7, 2};
station_t GOVCENTGREEN_SOUTH = {CS38_SW9, 2};
station_t GOVCENTGREEN_NORTH = {CS3_SW9, 2};
station_t GOVCENTGREEN_TO_PARKST = {CS4_SW9, 2};
station_t PARKSTGREEN_TO_GOVCENTGREEN = {CS30_SW4, 1};
station_t PARKSTGREEN_SOUTH = {CS24_SW7, 2};
station_t PARKSTGREEN_NORTH = {CS11_SW7, 2};
station_t PARKSTGREEN_TO_BOYLSTON = { CS13_SW9, 2};
station_t BOYLSTON_TO_PARKSTGREEN = { CS7_SW7, 2};
station_t BOYLSTON_SOUTH = { CS31_SW6, 2};
station_t BOYLSTON_NORTH = { CS30_SW6, 2};
station_t BOYLSTON_TO_ARLINGTON = { CS28_SW6, 2};
station_t ARLINGTON_TO_BOYLSTON = { CS29_SW6, 2};
station_t ARLINGTON_SOUTH = { CS26_SW6, 2};
station_t ARLINGTON_NORTH = { CS27_SW6, 2};
station_t ARLINGTON_TO_COPLEY = { CS15_SW6, 2};
station_t COPLEY_TO_ARLINGTON = { CS14_SW6, 2};
station_t COPLEY_SOUTH = { CS12_SW5, 2};
station_t COPLEY_NORTH = { CS11_SW5, 2};
station_t HYNES_SOUTH = { CS10_SW5, 2};
station_t HYNES_NORTH = { CS9_SW5, 2};
station_t KENMORE_SOUTH = { CS8_SW5, 2};
station_t KENMORE_NORTH = { CS7_SW5, 2};

const station_t *main_green_line_stations[] = {
    &MEDFORD_TUFTS_SOUTH,&MEDFORD_TUFTS_NORTH,&MEDFORD_TUFTS_TO_BALL_SQUARE,&BALL_SQUARE_TO_MEDFORD_TUFTS,
    &BALL_SQUARE_SOUTH,&BALL_SQUARE_NORTH,&BALL_SQUARE_TO_MAGOUN_SQUARE,&MAGOUN_SQUARE_TO_BALL_SQUARE,&MAGOUN_SQUARE_SOUTH,&MAGOUN_SQUARE_NORTH,
    &MAGOUN_SQUARE_TO_GILMAN_SQUARE,&GILMAN_SQUARE_TO_MAGOUN_SQUARE,&GILMAN_SQUARE_SOUTH,&GILMAN_SQUARE_NORTH,&GILMAN_SQUARE_TO_EAST_SOMERVILLE,
    &EAST_SOMERVILLE_TO_GILMAN_SQUARE,&EAST_SOMERVILLE_SOUTH,&EAST_SOMERVILLE_NORTH,&EAST_SOMERVILLE_TO_LECHMERE,&LECHMERE_TO_EAST_SOMERVILLE,
    &LECHMERE_SOUTH,&LECHMERE_NORTH,&UNION_SOUTH,&UNION_NORTH,&UNION_TO_LECHMERE,&LECHMERE_TO_UNION,&LECHMERE_TO_SCIENCEPARK,&SCIENCEPARK_TO_LECHMERE,
    &SCIENCEPARK_SOUTH,&SCIENCEPARK_NORTH,&SCIENCEPARK_TO_NSTATIONGREEN,&NSTATIONGREEN_TO_SCIENCEPARK,&NSTATIONGREEN_SOUTH,&NSTATIONGREEN_NORTH,
    &NSTATIONGREEN_TO_HAYMARKETGREEN,&HAYMARKETGREEN_TO_NSTATIONGREEN,&HAYMARKETGREEN_SOUTH,&HAYMARKETGREEN_NORTH,&HAYMARKETGREEN_TO_GOVCENTGREEN,
    &GOVCENTGREEN_TO_HAYMARKETGREEN,&GOVCENTGREEN_SOUTH,&GOVCENTGREEN_NORTH,&GOVCENTGREEN_TO_PARKST,&PARKSTGREEN_TO_GOVCENTGREEN,&PARKSTGREEN_SOUTH,&PARKSTGREEN_NORTH,
    &PARKSTGREEN_TO_BOYLSTON, &BOYLSTON_TO_PARKSTGREEN,&BOYLSTON_SOUTH,&BOYLSTON_NORTH,&BOYLSTON_TO_ARLINGTON,&ARLINGTON_TO_BOYLSTON,&ARLINGTON_SOUTH,&ARLINGTON_NORTH,
    &ARLINGTON_TO_COPLEY,&COPLEY_TO_ARLINGTON,&COPLEY_SOUTH,&COPLEY_NORTH,&HYNES_SOUTH,&HYNES_NORTH,&KENMORE_SOUTH,&KENMORE_NORTH
};



// Green Line - Branch B˛
//IMPORTANT NOTE:   Rev 1 of the hardware has a few duplicate stations
//                  and labelling errors. This mapping is set up to match what 

station_t BLANDFORD_IN = { CS6_SW3, 2};
station_t BLANDFORD_OUT = { CS5_SW4, 2};
station_t BU_EAST_IN = { CS5_SW3, 2};
station_t BU_EAST_OUT = { CS6_SW4, 2};
station_t BU_CENTRAL_IN = { CS7_SW3, 2};
station_t BU_CENTRAL_OUT = { CS7_SW4, 2};
station_t AMORY_ST_IN = { CS8_SW3, 2};
station_t AMORY_ST_OUT = { CS8_SW4, 2};
station_t BABCOCK_ST_IN = { CS10_SW3, 2};
station_t BABCOCK_ST_OUT = { CS9_SW4, 2};
station_t PACKARDS_CORNER_IN = { CS9_SW3, 2};
station_t PACKARDS_CORNER_OUT = { CS10_SW4, 2};
station_t HARVARD_AVE_IN = { CS11_SW3, 2};
station_t HARVARD_AVE_OUT = { CS11_SW4, 2};
station_t GRIGGS_ST_IN = { CS12_SW3, 2};
station_t GRIGGS_ST_OUT = { CS12_SW4, 2};
station_t ALLSTON_ST_IN = { CS13_SW3, 2};
station_t ALLSTON_ST_OUT = { CS14_SW3, 2};
station_t WARREN_ST_IN = { CS21_SW2, 2};
station_t WARREN_ST_OUT = { CS20_SW2, 2};
station_t WASHINGTON_ST_IN = { CS18_SW2, 2};
station_t WASHINGTON_ST_OUT = { CS19_SW2, 2};
station_t SUTHERLAND_RD_IN = { CS25_SW1, 2};
station_t SUTHERLAND_RD_OUT = { CS26_SW1, 2};
station_t CHISWICK_RD_IN = { CS24_SW1, 2};
station_t CHISWICK_RD_OUT = { CS23_SW1, 2};
station_t CHESTNUT_HILL_AVE_IN = { CS9_SW5, 1};
station_t CHESTNUT_HILL_AVE_OUT = { CS20_SW1, 2};
station_t SOUTH_ST_IN = { CS4_SW5, 1};
station_t SOUTH_ST_OUT = { CS21_SW1, 2};
station_t BOSTON_COLLEGE_TO_SOUTH_ST = { CS7_SW5, 1};
station_t SOUTH_ST_TO_BOSTON_COLLEGE = { CS22_SW1, 2};
station_t BOSTON_COLLEGE_IN = { CS15_SW5, 1};
station_t BOSTON_COLLEGE_OUT = { CS19_SW1, 2};

const station_t *b_green_line_stations[] = {
    &BLANDFORD_IN,
    &BLANDFORD_OUT,
    &BU_EAST_IN,
    &BU_EAST_OUT,
    &BU_CENTRAL_IN,
    &BU_CENTRAL_OUT,
    &AMORY_ST_IN,
    &AMORY_ST_OUT,
    &BABCOCK_ST_IN,
    &BABCOCK_ST_OUT,
    &PACKARDS_CORNER_IN,
    &PACKARDS_CORNER_OUT,
    &HARVARD_AVE_IN,
    &HARVARD_AVE_OUT,
    &GRIGGS_ST_IN,
    &GRIGGS_ST_OUT,
    &ALLSTON_ST_IN,
    &ALLSTON_ST_OUT,
    &WARREN_ST_IN,
    &WARREN_ST_OUT,
    &WASHINGTON_ST_IN,
    &WASHINGTON_ST_OUT,
    &SUTHERLAND_RD_IN,
    &SUTHERLAND_RD_OUT,
    &CHISWICK_RD_IN,
    &CHISWICK_RD_OUT,
    &CHESTNUT_HILL_AVE_IN,
    &CHESTNUT_HILL_AVE_OUT,
    &SOUTH_ST_IN,
    &SOUTH_ST_OUT,
    &BOSTON_COLLEGE_TO_SOUTH_ST,
    &SOUTH_ST_TO_BOSTON_COLLEGE,
    &BOSTON_COLLEGE_IN,
    &BOSTON_COLLEGE_OUT
};


station_t ST_MARYS_ST_SOUTH = { CS7_SW2, 2};
station_t ST_MARYS_ST_NORTH = { CS6_SW2, 2};
station_t HAWES_ST_SOUTH = { CS9_SW2, 2};
station_t HAWES_ST_NORTH = { CS8_SW2, 2};
station_t KENT_ST_SOUTH = { CS11_SW2, 2};
station_t KENT_ST_NORTH = { CS10_SW2, 2};
station_t ST_PAUL_ST_SOUTH = { CS13_SW2, 2};
station_t ST_PAUL_ST_NORTH = { CS12_SW2, 2};
station_t COOLIDGE_CORNER_SOUTH = { CS15_SW2, 2};
station_t COOLIDGE_CORNER_NORTH = { CS14_SW2, 2};
station_t SUMMIT_AVE_SOUTH = { CS17_SW2, 2};
station_t SUMMIT_AVE_NORTH = { CS16_SW2, 2};
station_t BRANDON_HALL_SOUTH = { CS9_SW1, 2};
station_t BRANDON_HALL_NORTH = { CS29_SW1, 2};
station_t FAIRBANKS_ST_SOUTH = { CS8_SW1, 2};
station_t FAIRBANKS_ST_NORTH = { CS10_SW5, 1};
station_t WASHINGTON_SQ_SOUTH = { CS7_SW1, 2};
station_t WASHINGTON_SQ_NORTH = { CS31_SW5, 1};
station_t TAPPAN_ST_SOUTH = { CS6_SW1, 2};
station_t TAPPAN_ST_NORTH = { CS2_SW5, 1};
station_t DEAN_RD_SOUTH = { CS5_SW1, 2};
station_t DEAN_RD_NORTH = { CS3_SW2, 2};
station_t ENGLEWOOD_AVE_SOUTH = { CS4_SW1, 2};
station_t ENGLEWOOD_AVE_NORTH = { CS2_SW2, 2};
station_t CLEVELAND_CIRCLE_SOUTH = { CS3_SW1, 2};
station_t CLEVELAND_CIRCLE_NORTH = { CS4_SW2, 2};

const station_t *c_green_line_stations[] = {
    &ST_MARYS_ST_SOUTH,
    &ST_MARYS_ST_NORTH,
    &HAWES_ST_SOUTH,
    &HAWES_ST_NORTH,
    &KENT_ST_SOUTH,
    &KENT_ST_NORTH,
    &ST_PAUL_ST_SOUTH,
    &ST_PAUL_ST_NORTH,
    &COOLIDGE_CORNER_SOUTH,
    &COOLIDGE_CORNER_NORTH,
    &SUMMIT_AVE_SOUTH,
    &SUMMIT_AVE_NORTH,
    &BRANDON_HALL_SOUTH,
    &BRANDON_HALL_NORTH,
    &FAIRBANKS_ST_SOUTH,
    &FAIRBANKS_ST_NORTH,
    &WASHINGTON_SQ_SOUTH,
    &WASHINGTON_SQ_NORTH,
    &TAPPAN_ST_SOUTH,
    &TAPPAN_ST_NORTH,
    &DEAN_RD_SOUTH,
    &DEAN_RD_NORTH,
    &ENGLEWOOD_AVE_SOUTH,
    &ENGLEWOOD_AVE_NORTH,
    &CLEVELAND_CIRCLE_SOUTH,
    &CLEVELAND_CIRCLE_NORTH
};

station_t KENMORE_TO_FENWAY = { CS5_SW5, 2};
station_t FENWAY_TO_KENMORE = { CS6_SW5, 2};
station_t FENWAY_SOUTH = { CS12_SW6, 2};
station_t FENWAY_NORTH = { CS13_SW6, 2};
station_t FENWAY_TO_LONGWOOD = { CS36_SW7, 2};
station_t LONGWOOD_TO_FENWAY = { CS13_SW7, 2};
station_t LONGWOOD_SOUTH = { CS11_SW6, 2};
station_t LONGWOOD_NORTH = { CS8_SW5, 1};
station_t LONGWOOD_TO_BROOKLINE_VILLAGE = { CS10_SW6, 2};
station_t BROOKLINE_VILLAGE_TO_LONGWOOD = { CS32_SW5, 1};
station_t BROOKLINE_VILLAGE_SOUTH = { CS9_SW6, 2};
station_t BROOKLINE_VILLAGE_NORTH = { CS31_SW7, 2};
station_t BROOKLINE_VILLAGE_TO_BROOKLINE_HILLS = { CS8_SW6, 2};
station_t BROOKLINE_HILLS_TO_BROOKLINE_VILLAGE = { CS35_SW7, 2};
station_t BROOKLINE_HILLS_SOUTH = { CS7_SW6, 2};
station_t BROOKLINE_HILLS_NORTH = { CS33_SW7, 2};
station_t BROOKLINE_HILLS_TO_BEACONSFIELD = { CS24_SW9, 2};
station_t BEACONSFIELD_TO_BROOKLINE_HILLS = { CS26_SW9, 2};
station_t BEACONSFIELD_SOUTH = { CS36_SW9, 2};
station_t BEACONSFIELD_NORTH = { CS31_SW9, 2};
station_t BEACONSFIELD_TO_RESERVOIR = { CS23_SW9, 2};
station_t RESERVOIR_TO_BEACONSFIELD = { CS3_SW5, 1};
station_t RESERVOIR_SOUTH = { CS9_SW8, 2};
station_t RESERVOIR_NORTH = { CS37_SW8, 2};
station_t RESERVOIR_TO_CHESTNUT_HILL = { CS2_SW8, 2};
station_t CHESTNUT_HILL_TO_RESERVOIR = { CS7_SW8, 2};
station_t CHESTNUT_HILL_SOUTH = { CS5_SW8, 2};
station_t CHESTNUT_HILL_NORTH = { CS4_SW8, 2};
station_t CHESTNUT_HILL_TO_NEWTON_CENTRE = { CS33_SW8, 2};
station_t NEWTON_CENTRE_TO_CHESTNUT_HILL = { CS35_SW8, 2};
station_t NEWTON_CENTRE_SOUTH = { CS2_SW6, 2};
station_t NEWTON_CENTRE_NORTH = { CS1_SW6, 2};
station_t NEWTON_CENTRE_TO_NEWTON_HIGHLANDS = { CS4_SW6, 2};
station_t NEWTON_HIGHLANDS_TO_NEWTON_CENTRE = { CS3_SW6, 2};
station_t NEWTON_HIGHLANDS_SOUTH = { CS6_SW6, 2};
station_t NEWTON_HIGHLANDS_NORTH = { CS5_SW6, 2};
station_t NEWTON_HIGHLANDS_TO_ELIOT = { CS4_SW5, 2};
station_t ELIOT_TO_NEWTON_HIGHLANDS = { CS3_SW5, 2};
station_t ELIOT_SOUTH = { CS2_SW5, 2};
station_t ELIOT_NORTH = { CS1_SW5, 2};
station_t ELIOT_TO_WABAN = { CS4_SW4, 2};
station_t WABAN_TO_ELIOT = { CS3_SW4, 2};
station_t WABAN_SOUTH = { CS1_SW4, 2};
station_t WABAN_NORTH = { CS2_SW4, 2};
station_t WABAN_TO_WOODLAND = { CS2_SW3, 2};
station_t WOODLAND_TO_WABAN = { CS3_SW3, 2};
station_t WOODLAND_SOUTH = { CS4_SW3, 2};
station_t WOODLAND_NORTH = { CS1_SW3, 2};
station_t WOODLAND_TO_RIVERSIDE = { CS5_SW2, 2};
station_t RIVERSIDE_TO_WOODLAND = { CS1_SW2, 2};
station_t RIVERSIDE_SOUTH = { CS2_SW1, 2};
station_t RIVERSIDE_NORTH = { CS1_SW1, 2};

const station_t *d_green_line_stations[] = {
    &KENMORE_TO_FENWAY,
    &FENWAY_TO_KENMORE,
    &FENWAY_SOUTH,
    &FENWAY_NORTH,
    &FENWAY_TO_LONGWOOD,
    &LONGWOOD_TO_FENWAY,
    &LONGWOOD_SOUTH,
    &LONGWOOD_NORTH,
    &LONGWOOD_TO_BROOKLINE_VILLAGE,
    &BROOKLINE_VILLAGE_TO_LONGWOOD,
    &BROOKLINE_VILLAGE_SOUTH,
    &BROOKLINE_VILLAGE_NORTH,
    &BROOKLINE_VILLAGE_TO_BROOKLINE_HILLS,
    &BROOKLINE_HILLS_TO_BROOKLINE_VILLAGE,
    &BROOKLINE_HILLS_SOUTH,
    &BROOKLINE_HILLS_NORTH,
    &BROOKLINE_HILLS_TO_BEACONSFIELD,
    &BEACONSFIELD_TO_BROOKLINE_HILLS,
    &BEACONSFIELD_SOUTH,
    &BEACONSFIELD_NORTH,
    &BEACONSFIELD_TO_RESERVOIR,
    &RESERVOIR_TO_BEACONSFIELD,
    &RESERVOIR_SOUTH,
    &RESERVOIR_NORTH,
    &RESERVOIR_TO_CHESTNUT_HILL,
    &CHESTNUT_HILL_TO_RESERVOIR,
    &CHESTNUT_HILL_SOUTH,
    &CHESTNUT_HILL_NORTH,
    &CHESTNUT_HILL_TO_NEWTON_CENTRE,
    &NEWTON_CENTRE_TO_CHESTNUT_HILL,
    &NEWTON_CENTRE_SOUTH,
    &NEWTON_CENTRE_NORTH,
    &NEWTON_CENTRE_TO_NEWTON_HIGHLANDS,
    &NEWTON_HIGHLANDS_TO_NEWTON_CENTRE,
    &NEWTON_HIGHLANDS_SOUTH,
    &NEWTON_HIGHLANDS_NORTH,
    &NEWTON_HIGHLANDS_TO_ELIOT,
    &ELIOT_TO_NEWTON_HIGHLANDS,
    &ELIOT_SOUTH,
    &ELIOT_NORTH,
    &ELIOT_TO_WABAN,
    &WABAN_TO_ELIOT,
    &WABAN_SOUTH,
    &WABAN_NORTH,
    &WABAN_TO_WOODLAND,
    &WOODLAND_TO_WABAN,
    &WOODLAND_SOUTH,
    &WOODLAND_NORTH,
    &WOODLAND_TO_RIVERSIDE,
    &RIVERSIDE_TO_WOODLAND,
    &RIVERSIDE_SOUTH,
    &RIVERSIDE_NORTH
};


station_t PRUDENTIAL_SOUTH = { CS1_SW9, 2};
station_t PRUDENTIAL_NORTH = { CS2_SW9, 2};
station_t PRUDENTIAL_TO_SYMPHONY = { CS16_SW9, 2};
station_t SYMPHONY_TO_PRUDENTIAL = { CS15_SW9, 2};
station_t SYMPHONY_SOUTH = { CS12_SW9, 2};
station_t SYMPHONY_NORTH = { CS14_SW9, 2};
station_t SYMPHONY_TO_NORTHEASTERN = { CS3_SW7, 2};
station_t NORTHEASTERN_TO_SYMPHONY = { CS2_SW7, 2};
station_t NORTHEASTERN_SOUTH = { CS1_SW7, 2};
station_t NORTHEASTERN_NORTH = { CS37_SW7, 2};
station_t NORTHEASTERN_TO_MFA = { CS28_SW7, 2};
station_t MFA_TO_NORTHEASTERN = { CS23_SW7, 2};
station_t MFA_SOUTH = { CS29_SW7, 2};
station_t MFA_NORTH = { CS27_SW7, 2};
station_t MFA_TO_LONGWOOD_MEDICAL_AREA = { CS25_SW7, 2};
station_t LONGWOOD_MEDICAL_AREA_TO_MFA = { CS30_SW7, 2};
station_t LONGWOOD_MEDICAL_AREA_SOUTH = { CS26_SW7, 2};
station_t LONGWOOD_MEDICAL_AREA_NORTH = { CS39_SW8, 2};
station_t BRIGHAM_CIRCLE_SOUTH = { CS24_SW8, 2};
station_t BRIGHAM_CIRCLE_NORTH = { CS23_SW8, 2};
station_t FENWOOD_RD_SOUTH = { CS20_SW8, 2};
station_t FENWOOD_RD_NORTH = { CS19_SW8, 2};
station_t MISSION_PARK_SOUTH = { CS25_SW8, 2};
station_t MISSION_PARK_NORTH = { CS21_SW8, 2};
station_t RIVERWAY_SOUTH = { CS26_SW8, 2};
station_t RIVERWAY_NORTH = { CS22_SW8, 2};
station_t BACK_OF_THE_HILL_SOUTH = { CS11_SW8, 2};
station_t BACK_OF_THE_HILL_NORTH = { CS6_SW8, 2};
station_t HEATH_ST_SOUTH = { CS3_SW8, 2};
station_t HEATH_ST_NORTH = { CS38_SW8, 2};

const station_t *e_green_line_stations[] = {
    &PRUDENTIAL_SOUTH,
    &PRUDENTIAL_NORTH,
    &PRUDENTIAL_TO_SYMPHONY,
    &SYMPHONY_TO_PRUDENTIAL,
    &SYMPHONY_SOUTH,
    &SYMPHONY_NORTH,
    &SYMPHONY_TO_NORTHEASTERN,
    &NORTHEASTERN_TO_SYMPHONY,
    &NORTHEASTERN_SOUTH,
    &NORTHEASTERN_NORTH,
    &NORTHEASTERN_TO_MFA,
    &MFA_TO_NORTHEASTERN,
    &MFA_SOUTH,
    &MFA_NORTH,
    &MFA_TO_LONGWOOD_MEDICAL_AREA,
    &LONGWOOD_MEDICAL_AREA_TO_MFA,
    &LONGWOOD_MEDICAL_AREA_SOUTH,
    &LONGWOOD_MEDICAL_AREA_NORTH,
    &BRIGHAM_CIRCLE_SOUTH,
    &BRIGHAM_CIRCLE_NORTH,
    &FENWOOD_RD_SOUTH,
    &FENWOOD_RD_NORTH,
    &MISSION_PARK_SOUTH,
    &MISSION_PARK_NORTH,
    &RIVERWAY_SOUTH,
    &RIVERWAY_NORTH,
    &BACK_OF_THE_HILL_SOUTH,
    &BACK_OF_THE_HILL_NORTH,
    &HEATH_ST_SOUTH,
    &HEATH_ST_NORTH
};



int main_green_len = sizeof(main_green_line_stations) / sizeof(main_green_line_stations[0]);
int b_green_len = sizeof(b_green_line_stations) / sizeof(b_green_line_stations[0]);
int c_green_len  = sizeof(c_green_line_stations) / sizeof(c_green_line_stations[0]);
int d_green_len = sizeof(d_green_line_stations) / sizeof(d_green_line_stations[0]);
int e_green_len = sizeof(e_green_line_stations) / sizeof(e_green_line_stations[0]);



//need to add parameters for i2c device list so that the function knows which device it is picking.
uint32_t setStation(const station_t *station, int amplitude, i2c_master_dev_handle_t U1, i2c_master_dev_handle_t U2){

    uint32_t result = 0;
    if(station->chip==1){
        result = writeLED(station->addr, amplitude, U1);
    }

    else if (station->chip==2)
    {
        result = writeLED(station->addr, amplitude, U2);
    }
    else{
        result = 0;
    }
    return result;
    

}

uint32_t clearStation(const station_t *station, i2c_master_dev_handle_t U1, i2c_master_dev_handle_t U2){

    uint32_t result = 0;
    if(station->chip==1){
        result = writeLED(station->addr, 00, U1);
    }

    else if (station->chip==2)
    {
        result = writeLED(station->addr, 00, U2);
    }
    else{
        result=0;
    }
    return result;
    

}









